name: "Provision and Initialise Containerised Lambda Function on AWS"
description: "Automatically creates a new ECR Repository, Lambda Function, Policy and Pipeline user."
author: "Pierre Tharreau"
inputs:
  new-function-name:
    description: "Name of the new lambda function to create"
    required: true
  aws-access-key-id:
    description: "AWS Credentials for user assumed when initialising resources"
    required: true
  aws-secret-access-key:
    description: "AWS Credentials for user assumed when initialising resources"
    required: true
  aws-region:
    description: "AWS region in which to initialise resources"
    required: true

outputs:
  test:
    description: "Test outputs"
    value: ${{ steps.main-step.outputs.test }}

runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: python -m pip install -r requirements.txt
      shell: bash

    - name: Run the actual action in python
      id: main-step
      env:
        NEW_FUNCTION_NAME: ${{ inputs.new-function-name }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: python main.py
      shell: bash
# runs:
#   using: "docker"
#   image: "Dockerfile"
